### PR TITLE
Github workflow and README fixes

### PR DESCRIPTION
**Pull request by Yimura**
Hi there back with more 👋 

# What is this?
Previously I would pull the repo locally and then deploy it on my local server, having the images be automatically made makes it easier for me to update my local deployment of GTAV-NativeDB.
So what I've made in this PR is a Github workflow that builds a docker image every time you push to the `master` branch.
I've setup the workflow to be completely independent of the repository owner, it should be ready to merge as-is without any changes. The package will be automatically linked to this repository, you can take a look at my repo to see how it looks.

I've also added a devcontainer configuration, however that was more for personal testing and I'm happy to take it out if you want.

## Additions
 - GH Workflow file to build a docker image on the current repository
 - devcontainer config (I use this to not dirty my desktop with different node installations)

## Fixes
 - Fixed README logo image not showing up
 - Fixed small typo in README

## Setup

To get this to work there are a few steps that you'll have to take.
1. Create a [personal access token](https://github.com/settings/tokens/new) with `package:write` and `repo:full` access (ticking `package:write` will automatically add `repo:full`)
2. Set an expiry date on your token, take something that you feel comfortable with.
3. Add the [token to your repository secrets](https://github.com/DottieDot/GTAV-NativeDB/settings/secrets/actions/new) with `PACKAGE_WRITE_TOKEN` as name.
4. Merge into master and watch build [here](https://github.com/DottieDot/GTAV-NativeDB/actions/workflows/build-latest.yml).
5. After the build is a completed a new package should become visible on your account, however it will be set to private visibility by default.
6. Go to [your package settings](https://github.com/users/DottieDot/packages/container/gtav-nativedb/settings) and change the visibility to **public**.

## Issues
~~I see you've added environment variables to set the application title, description, etc...~~

~~I will investigate some more into fixing this for docker builds, would you want separate images to be built for RDR3 and GTA5?~~

### CODE REVIEW

**Comment by DottieDot** [comment]
Very neat, I'll look into merging this soon.  

As for:
> I see you've added environment variables to set the application title, description, etc...
> 
> I will investigate some more into fixing this for docker builds, would you want separate images to be built for RDR3 and GTA5?

Considering that the environment variables are injected at build time, having two seperate docker images is probably the only option.

**Comment by Yimura** [comment]
I'll fix that tomorrow evening.

**Comment by Yimura** [comment]
Ok that's fixed, basically I parse the `.env.example` file. On thing to note however is that the action makes that assumption that whatever it commented is the RDR3 env variables and whatever isn't commented is for GTA V.

You can change the contents of the variables whenever as long as the file keeps the RDR3 variables commented and GTA V variables uncommented.

I also saw that the browserlist was outdated but I'm leaving that for you to update.

**Comment by DottieDot** [comment]
> Ok that's fixed, basically I parse the `.env.example` file. One thing to note however is that the action makes that assumption that whatever it commented is the RDR3 env variables and whatever isn't commented is for GTA V.
> 
> You can change the contents of the variables whenever as long as the file keeps the RDR3 variables commented and GTA V variables uncommented.
> 
> I also saw that the browserlist was outdated but I'm leaving that for you to update.

Thanks! I'll try merging tomorrow

**Comment by DottieDot** [comment]
It's all up and running, thanks again 🙂. https://github.com/DottieDot/GTAV-NativeDB/actions/runs/5728071063

**Pull request merged**
